begin;

create table if not exists public.client_errors (
  id bigint generated by default as identity primary key,
  message text not null check (length(message) between 1 and 1200),
  stack text,
  path text,
  source text,
  component_stack text,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.client_errors enable row level security;
drop policy if exists "client_errors: admin read" on public.client_errors;
create policy "client_errors: admin read" on public.client_errors
  for select to authenticated
  using ((auth.jwt() ->> 'email') = 'romainpechabrier@gmail.com');

create index if not exists client_errors_occurred_idx
  on public.client_errors (occurred_at desc);

commit;
