begin;

create table if not exists public.learning_review_cards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  review_key text not null check (length(review_key) between 1 and 120),
  payload jsonb not null check (jsonb_typeof(payload) = 'object' and octet_length(payload::text) <= 12000),
  reviewed_at timestamptz not null default now(),
  unique (user_id, review_key)
);

alter table public.learning_review_cards enable row level security;

drop policy if exists "learning_review_cards: self read" on public.learning_review_cards;
create policy "learning_review_cards: self read"
  on public.learning_review_cards for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "learning_review_cards: self insert" on public.learning_review_cards;
create policy "learning_review_cards: self insert"
  on public.learning_review_cards for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "learning_review_cards: self update" on public.learning_review_cards;
create policy "learning_review_cards: self update"
  on public.learning_review_cards for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "learning_review_cards: self delete" on public.learning_review_cards;
create policy "learning_review_cards: self delete"
  on public.learning_review_cards for delete to authenticated
  using (auth.uid() = user_id);

create index if not exists learning_review_cards_user_date_idx
  on public.learning_review_cards (user_id, reviewed_at desc);

revoke all on table public.learning_review_cards from anon;
grant select, insert, update, delete on table public.learning_review_cards to authenticated;
grant usage, select on sequence public.learning_review_cards_id_seq to authenticated;

commit;
