begin;

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (length(event_name) between 1 and 80),
  anonymous_id uuid not null,
  pathname text,
  properties jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
alter table public.product_events enable row level security;
drop policy if exists "product_events: admin read" on public.product_events;
create policy "product_events: admin read" on public.product_events for select to authenticated
  using ((auth.jwt() ->> 'email') = 'romainpechabrier@gmail.com');
create index if not exists product_events_name_date_idx on public.product_events (event_name, occurred_at desc);
create index if not exists product_events_visitor_date_idx on public.product_events (anonymous_id, occurred_at);

create table if not exists public.purchase_consents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  stripe_checkout_session_id text not null unique,
  purchase_attempt_id uuid not null unique,
  plan text not null check (plan in ('mensuel', 'special_examen')),
  terms_version text not null,
  immediate_access_accepted boolean not null check (immediate_access_accepted),
  consented_at timestamptz not null,
  created_at timestamptz not null default now()
);
alter table public.purchase_consents enable row level security;
drop policy if exists "purchase_consents: self read" on public.purchase_consents;
create policy "purchase_consents: self read" on public.purchase_consents for select to authenticated using (auth.uid() = user_id);
drop policy if exists "purchase_consents: admin read" on public.purchase_consents;
create policy "purchase_consents: admin read" on public.purchase_consents for select to authenticated
  using ((auth.jwt() ->> 'email') = 'romainpechabrier@gmail.com');

create table if not exists public.pilot_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('eleve', 'parent', 'enseignant')),
  usefulness smallint not null check (usefulness between 1 and 5),
  ease smallint not null check (ease between 1 and 5),
  would_recommend boolean not null,
  comment text not null default '' check (length(comment) <= 2000),
  created_at timestamptz not null default now()
);
alter table public.pilot_feedback enable row level security;
drop policy if exists "pilot_feedback: self read" on public.pilot_feedback;
create policy "pilot_feedback: self read" on public.pilot_feedback for select to authenticated using (auth.uid() = user_id);
drop policy if exists "pilot_feedback: admin read" on public.pilot_feedback;
create policy "pilot_feedback: admin read" on public.pilot_feedback for select to authenticated
  using ((auth.jwt() ->> 'email') = 'romainpechabrier@gmail.com');
create index if not exists pilot_feedback_created_idx on public.pilot_feedback (created_at desc);

create table if not exists public.learning_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  skill_id text not null,
  chapter_id text not null,
  correct boolean not null,
  error_code text,
  response_time_ms integer check (response_time_ms between 0 and 1800000),
  assisted boolean not null default false,
  attempted_at timestamptz not null default now()
);
alter table public.learning_attempts enable row level security;
drop policy if exists "learning_attempts: self read" on public.learning_attempts;
create policy "learning_attempts: self read" on public.learning_attempts for select to authenticated using (auth.uid() = user_id);
drop policy if exists "learning_attempts: admin read" on public.learning_attempts;
create policy "learning_attempts: admin read" on public.learning_attempts for select to authenticated
  using ((auth.jwt() ->> 'email') = 'romainpechabrier@gmail.com');
create index if not exists learning_attempts_user_date_idx on public.learning_attempts (user_id, attempted_at desc);
create index if not exists learning_attempts_error_idx on public.learning_attempts (error_code, attempted_at desc) where error_code is not null;

create or replace function public.record_learning_attempt(
  p_skill_id text,
  p_chapter_id text,
  p_correct boolean,
  p_activity_date date,
  p_error_code text,
  p_response_time_ms integer,
  p_assisted boolean
)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_durable_correct boolean := p_correct and not coalesce(p_assisted, false);
begin
  if v_user_id is null then raise exception 'Non authentifié'; end if;
  if p_skill_id is null or length(trim(p_skill_id)) not between 1 and 200 then raise exception 'Compétence invalide'; end if;
  if p_chapter_id is null or length(trim(p_chapter_id)) not between 1 and 120 then raise exception 'Chapitre invalide'; end if;
  if p_correct is null then raise exception 'Résultat invalide'; end if;
  if p_activity_date is null or p_activity_date not between current_date - 1 and current_date + 1 then raise exception 'Date invalide'; end if;
  if p_error_code is not null and length(p_error_code) > 80 then raise exception 'Catégorie invalide'; end if;
  if p_response_time_ms is not null and p_response_time_ms not between 0 and 1800000 then raise exception 'Durée invalide'; end if;

  insert into public.learning_attempts (user_id, skill_id, chapter_id, correct, error_code, response_time_ms, assisted, attempted_at)
  values (v_user_id, trim(p_skill_id), trim(p_chapter_id), p_correct, case when p_correct then null else p_error_code end, p_response_time_ms, coalesce(p_assisted, false), v_now);

  insert into public.skill_mastery as sm (
    user_id, skill_id, chapter_id, attempts, correct, interval_stage,
    last_correct, last_practiced_at, next_review_at, updated_at
  ) values (
    v_user_id, trim(p_skill_id), trim(p_chapter_id), 1, case when p_correct then 1 else 0 end,
    case when v_durable_correct then 1 else 0 end, p_correct, v_now,
    case when v_durable_correct then v_now + interval '2 days' else v_now end, v_now
  )
  on conflict (user_id, skill_id) do update set
    chapter_id = excluded.chapter_id,
    attempts = sm.attempts + 1,
    correct = sm.correct + case when p_correct then 1 else 0 end,
    interval_stage = case when v_durable_correct then least(sm.interval_stage + 1, 4) else 0 end,
    last_correct = p_correct,
    last_practiced_at = v_now,
    next_review_at = case
      when not v_durable_correct then v_now
      when least(sm.interval_stage + 1, 4) = 1 then v_now + interval '2 days'
      when least(sm.interval_stage + 1, 4) = 2 then v_now + interval '7 days'
      when least(sm.interval_stage + 1, 4) = 3 then v_now + interval '14 days'
      else v_now + interval '28 days'
    end,
    updated_at = v_now;

  insert into public.daily_activity as da (user_id, activity_date, attempts, correct, updated_at)
  values (v_user_id, p_activity_date, 1, case when p_correct then 1 else 0 end, v_now)
  on conflict (user_id, activity_date) do update set
    attempts = da.attempts + 1,
    correct = da.correct + case when p_correct then 1 else 0 end,
    updated_at = v_now;
end;
$$;

revoke execute on function public.record_learning_attempt(text, text, boolean, date) from authenticated;
revoke all on function public.record_learning_attempt(text, text, boolean, date, text, integer, boolean) from public;
grant execute on function public.record_learning_attempt(text, text, boolean, date, text, integer, boolean) to authenticated;

commit;
