export const CYCLE_LANDINGS = {
  college: {
    label: "collège",
    h1: "Maths au collège : cours, méthodes et exercices corrigés",
    title: "Maths collège : cours et exercices corrigés | RéussiMaths",
    description: "Cours, méthodes et exercices corrigés de maths de la 6e à la 3e pour comprendre les notions, s’entraîner et préparer le Brevet.",
    intro: "De la 6e à la 3e, RéussiMaths aide l’élève à consolider les bases, comprendre les méthodes et s’entraîner sur les chapitres étudiés en classe. Chaque niveau donne accès à des exercices progressifs, des aides et des corrections expliquées.",
    details: "Nombres, fractions, proportionnalité, calcul littéral, géométrie, fonctions, statistiques et probabilités sont travaillés au fil du collège. En 3e, des entraînements transversaux permettent aussi de préparer les automatismes et les raisonnements attendus au Brevet.",
    topics: ["Nombres, calculs et fractions", "Proportionnalité et pourcentages", "Calcul littéral et équations", "Géométrie et grandeurs", "Statistiques et probabilités", "Révisions du Brevet en 3e"],
  },
  lycee: {
    label: "lycée",
    h1: "Maths au lycée : cours, méthodes et exercices corrigés",
    title: "Maths lycée : cours et exercices corrigés | RéussiMaths",
    description: "Cours, méthodes et exercices corrigés de maths de la Seconde à la Terminale, en voie générale ou technologique.",
    intro: "Au lycée, RéussiMaths accompagne les élèves de Seconde, de Première et de Terminale dans les notions du programme et les automatismes indispensables. Les parcours s’adaptent à la voie générale, à la spécialité mathématiques et aux séries technologiques.",
    details: "Fonctions, suites, dérivation, probabilités, statistiques, géométrie et algorithmique sont abordées avec des exercices ciblés et des corrections détaillées. L’objectif est de comprendre la méthode, puis de savoir la réutiliser seul dans un exercice différent.",
    topics: ["Fonctions et représentations graphiques", "Suites numériques", "Dérivation et variations", "Probabilités et statistiques", "Géométrie repérée et dans l’espace", "Algorithmique et Python"],
  },
};

export const LEVEL_LANDINGS = {
  sixieme: {
    name: "6e", cycle: "college",
    title: "Maths 6e : programme, cours et exercices | RéussiMaths",
    description: "Maths 6e : cours gratuits, méthodes et exercices corrigés sur les nombres, fractions, proportionnalité, géométrie et grandeurs.",
    h1: "Maths 6e : programme, cours et exercices corrigés",
    intro: "En 6e, l’élève consolide les nombres entiers et décimaux, découvre de nouveaux usages des fractions et apprend à résoudre des problèmes en organisant sa démarche.",
    method: "RéussiMaths propose des questions progressives, des aides lorsqu’une difficulté est repérée et des corrections qui explicitent les étapes du raisonnement.",
    topics: ["Nombres entiers et décimaux", "Fractions et droite graduée", "Proportionnalité simple", "Calculs et problèmes", "Figures géométriques", "Longueurs, aires et volumes"],
  },
  cinquieme: {
    name: "5e", cycle: "college",
    title: "Maths 5e : programme, cours et exercices | RéussiMaths",
    description: "Maths 5e : cours et exercices corrigés sur les fractions, nombres relatifs, proportionnalité, calcul littéral, géométrie et statistiques.",
    h1: "Maths 5e : programme, méthodes et exercices corrigés",
    intro: "En 5e, les fractions, les nombres relatifs et la proportionnalité prennent une place importante. Le calcul littéral et le raisonnement géométrique commencent aussi à se structurer.",
    method: "Les exercices permettent d’identifier la méthode adaptée, de corriger les erreurs fréquentes et de revoir les notions qui ne sont pas encore solides.",
    topics: ["Fractions et nombres relatifs", "Proportionnalité et pourcentages", "Premières expressions littérales", "Angles et triangles", "Symétrie centrale", "Statistiques et probabilités"],
  },
  quatrieme: {
    name: "4e", cycle: "college",
    title: "Maths 4e : programme, cours et exercices | RéussiMaths",
    description: "Maths 4e : cours et exercices corrigés de calcul littéral, équations, puissances, Pythagore, Thalès, statistiques et probabilités.",
    h1: "Maths 4e : programme, méthodes et exercices corrigés",
    intro: "En 4e, l’élève développe le calcul littéral, les équations et les puissances tout en apprenant à choisir et rédiger une démonstration géométrique.",
    method: "RéussiMaths entraîne séparément les automatismes et les problèmes, avec des aides graduées pour comprendre pourquoi une méthode fonctionne et savoir la réutiliser.",
    topics: ["Nombres relatifs et fractions", "Puissances", "Calcul littéral et équations", "Théorème de Pythagore", "Théorème de Thalès", "Statistiques et probabilités"],
  },
  troisieme: {
    name: "3e", cycle: "college",
    title: "Maths 3e et Brevet : cours et exercices corrigés | RéussiMaths",
    description: "Maths 3e et Brevet : cours, méthodes et exercices corrigés sur les fonctions, le calcul littéral, la géométrie, les statistiques et probabilités.",
    h1: "Maths 3e : programme et préparation au Brevet",
    intro: "En 3e, les notions étudiées au collège sont mobilisées dans des problèmes plus complets. Les fonctions, le calcul littéral, la géométrie et les données sont essentiels pour préparer le Brevet.",
    method: "Les entraînements alternent questions ciblées et exercices transversaux afin de choisir une méthode sans qu’elle soit toujours annoncée dans l’énoncé.",
    topics: ["Calcul littéral et équations", "Fonctions linéaires et affines", "Thalès, Pythagore et trigonométrie", "Statistiques et probabilités", "Algorithmique", "Révisions et exercices type Brevet"],
  },
  seconde: {
    name: "2nde", cycle: "lycee",
    title: "Maths Seconde : programme, cours et exercices | RéussiMaths",
    description: "Maths Seconde : cours et exercices corrigés sur les nombres, fonctions, vecteurs, géométrie, statistiques, probabilités et Python.",
    h1: "Maths Seconde : programme, méthodes et exercices corrigés",
    intro: "En Seconde, l’élève approfondit le calcul et les fonctions, découvre les vecteurs et développe son autonomie dans la résolution de problèmes.",
    method: "RéussiMaths relie les automatismes aux exercices de raisonnement et revient sur les prérequis du collège lorsqu’ils bloquent une notion du lycée.",
    topics: ["Nombres et calculs", "Fonctions et variations", "Équations et inéquations", "Vecteurs et géométrie repérée", "Statistiques et probabilités", "Algorithmique et Python"],
  },
  "premiere-spe": {
    name: "Première spécialité", cycle: "lycee",
    title: "Maths Première spécialité : cours et exercices | RéussiMaths",
    description: "Maths Première spécialité : cours et exercices corrigés sur les fonctions, dérivation, suites, probabilités, géométrie et Python.",
    h1: "Maths Première spécialité : programme et exercices corrigés",
    intro: "En Première spécialité, les fonctions, la dérivation et les suites deviennent des outils majeurs. Les probabilités, la géométrie et l’algorithmique complètent la formation.",
    method: "Les exercices ciblent les techniques de calcul, la lecture des hypothèses et la rédaction, puis vérifient que la méthode est réutilisable dans un contexte nouveau.",
    topics: ["Second degré", "Dérivation et variations", "Suites numériques", "Fonction exponentielle", "Probabilités conditionnelles", "Géométrie et algorithmique"],
  },
  "premiere-non-spe": {
    name: "Première non-spécialité", cycle: "lycee",
    title: "Maths Première non-spécialité : cours et exercices | RéussiMaths",
    description: "Maths Première sans spécialité : automatismes, fonctions, statistiques, probabilités et exercices corrigés pour consolider les notions utiles.",
    h1: "Maths Première non-spécialité : cours et automatismes",
    intro: "En Première sans spécialité mathématiques, l’objectif est de conserver des outils solides pour interpréter des données, raisonner avec des fonctions et maîtriser les calculs utiles.",
    method: "RéussiMaths privilégie des séances courtes et régulières pour entretenir les automatismes et comprendre les méthodes plutôt que les apprendre sans contexte.",
    topics: ["Automatismes de calcul", "Proportions et évolutions", "Fonctions et lectures graphiques", "Statistiques", "Probabilités", "Résolution de problèmes"],
  },
  "premiere-techno": {
    name: "Première technologique", cycle: "lycee",
    title: "Maths Première technologique : cours et exercices | RéussiMaths",
    description: "Maths Première technologique : cours et exercices corrigés sur les fonctions, dérivation, suites, statistiques, probabilités et algorithmique.",
    h1: "Maths Première technologique : programme et exercices corrigés",
    intro: "En Première technologique, les fonctions, les suites et les statistiques servent à modéliser des situations concrètes. Les automatismes de calcul restent indispensables.",
    method: "Les exercices s’appuient sur des tableaux, des graphiques et des situations contextualisées, avec une correction détaillée de chaque étape utile.",
    topics: ["Automatismes", "Fonctions et dérivation", "Suites numériques", "Évolutions et pourcentages", "Statistiques et probabilités", "Algorithmique et Python"],
  },
  "terminale-spe": {
    name: "Terminale spécialité", cycle: "lycee",
    title: "Maths Terminale spécialité : cours et exercices | RéussiMaths",
    description: "Maths Terminale spécialité : cours et exercices corrigés sur les suites, limites, dérivation, exponentielle, logarithme, probabilités et géométrie.",
    h1: "Maths Terminale spécialité : programme et préparation au Bac",
    intro: "En Terminale spécialité, les outils d’analyse, les probabilités et la géométrie sont mobilisés dans des raisonnements plus longs et dans la préparation du Bac.",
    method: "RéussiMaths travaille à la fois les automatismes, le choix de la démarche et la vérification des hypothèses afin de rendre les méthodes réellement disponibles le jour de l’épreuve.",
    topics: ["Suites, limites et continuité", "Dérivation et convexité", "Exponentielle et logarithme", "Calcul intégral", "Probabilités", "Géométrie dans l’espace"],
  },
  "terminale-techno": {
    name: "Terminale technologique", cycle: "lycee",
    title: "Maths Terminale technologique : cours et exercices | RéussiMaths",
    description: "Maths Terminale technologique : cours et exercices corrigés sur les suites, fonctions, dérivation, logarithme, statistiques et probabilités.",
    h1: "Maths Terminale technologique : programme et exercices corrigés",
    intro: "En Terminale technologique, les fonctions, les suites, les statistiques et les probabilités permettent d’étudier et de prévoir des évolutions dans des contextes variés.",
    method: "Les entraînements mettent l’accent sur l’interprétation des résultats, la maîtrise de la calculatrice et la rédaction des étapes attendues au Bac.",
    topics: ["Automatismes", "Suites et évolutions", "Fonctions et dérivation", "Exponentielle et logarithme", "Statistiques à deux variables", "Probabilités et loi binomiale"],
  },
};

export function getLevelLanding(levelId) {
  return LEVEL_LANDINGS[levelId];
}
